#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_PORT				8888
#define DEFAULT_PROCESS_COUNT		2

#define DEFAULT_TYPE_POLL			0
#define DEFAULT_TYPE_EPOLL_EDGE		1
#define DEFAULT_TYPE_EPOLL_LEVEL	2

#endif
